## 01. 텐서 초기화
- 초기화: 텐서에 특정 값을 채워서 생성하는 것


In [2]:
import torch
torch.__version__

'2.5.1'

### 1-1. 초기화 되지 않은 텐서
- 특정한 값이 채워지지 않은 상태로 생성하는 것

In [4]:
tensor = torch.empty(4, 2)
print(tensor)

tensor([[-3.3157e+12,  1.1224e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


### 1-2. 상수로 초기화된 텐서
- torch.zeros()
- torch.ones()


In [11]:
a = torch.ones(3, 4, dtype=torch.long) #dtype: 데이터타입 지정
b = torch.zeros(2, 2)

print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


### 1.3 무작위하게 초기화된 Tensor
- torch.rand : 0~1 사이의 값으로 무작위로 초기화
- torch.randn : 표준정규분포에서 무작위로 초기화

In [15]:
a = torch.rand(3, 3) # 0~1 사이의 값으로 무작위로 초기화
b = torch.randn(3, 3) # 표준정규분포에서 무작위로 초기화
print(a)
print(b)

tensor([[0.6738, 0.4366, 0.3017],
        [0.4751, 0.9730, 0.4017],
        [0.6309, 0.0245, 0.9563]])
tensor([[ 0.0274, -1.2048,  0.8598],
        [-0.5414,  0.8068, -0.6011],
        [-0.4358, -1.3108,  0.8917]])


### 1-4. 직접 인력한 값으로 초기화


In [17]:
a = torch.tensor([[1, 2.3]])
a

tensor([[1.0000, 2.3000]])

### 1-5. NumPy 배열로부터 초기화

In [28]:
import numpy as np
nd_arr= np.array([1,2,3])
a = torch.from_numpy(nd_arr)

# numpy array로 변환
b = torch.tensor([1,2,3,4,5])
new_nd = b.numpy()
new_nd[2] = 100
print(new_nd)
print(b)

[  1   2 100   4   5]
tensor([  1,   2, 100,   4,   5])


### 1-6. 특정 텐서와 같은 타입, 무작위로 값을 채움

In [26]:
a = torch.ones(3, 4, dtype=torch.long)
b = torch.rand_like(a, dtype=torch.float)
b

tensor([[0.9350, 0.0773, 0.4726, 0.0962],
        [0.0635, 0.5671, 0.6701, 0.1693],
        [0.0665, 0.0583, 0.1344, 0.9294]])

### 1-7. 텐서의 속성

In [33]:
tensor = torch.rand(3, 4, dtype=torch.float64)
print(f"Shape: {tensor.shape}") 
print(f"Size: {tensor.size()}") 
print(f"Dtype: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([3, 4])
Size: torch.Size([3, 4])
Dtype: torch.float64
Device: cpu


### 1-8. 특징 타입의 텐서 생성

In [44]:
tensor = torch.rand(3, 4, dtype=torch.float64)

float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.dtype)

int_tensor = torch.FloatTensor([1.1,2.3,3.4])
print(int_tensor)
print(int_tensor.dtype)

torch.float32
tensor([1.1000, 2.3000, 3.4000])
torch.float32


### 1-9. 데이터 타입 캐스팅


In [46]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())

int_tensor = torch.FloatTensor([1,2,3])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10. CUDA Tensor

In [5]:

a = torch.ones(3,4, dtype=torch.long)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

## 1-11. 다차원 Tensor 표현

### 1-11-1 0D Tensor(Scalar)
- 0D Tensor(scalar) : 하나의 값을 담고 있는 텐서


In [6]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


### 1-11-2 1D Tensor(Vector)
- 1D Tensor(Vector) : 값들을 저장하고 있는 리스트와 유사하 텐서

In [8]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


### 1-11-3 2D Tensor(Matrix)
- 2D Tensor(Matrix) : 행랼과 같은 모양으로 두개의 축이 존재

In [10]:
t2 = torch.tensor([[1, 2, 3],[4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### 1-11-4 3D Tensor(cube)
- 큐브와 같은 형태로 세 개의 축이 존재

In [14]:
t3 = torch.tensor([[[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]],
                  [[1,2], [4,5], [7,8]]
                  ])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([4, 3, 2])
tensor([[[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]],

        [[1, 2],
         [4, 5],
         [7, 8]]])


### 1-11-4. 4D Tensor
- 4개의 축

In [18]:
t4 = torch.rand(2,3,4,5)
t4

tensor([[[[0.5505, 0.5343, 0.1070, 0.0571, 0.1303],
          [0.0577, 0.8142, 0.5617, 0.0881, 0.6031],
          [0.2214, 0.6186, 0.3857, 0.0366, 0.3336],
          [0.0019, 0.6350, 0.2710, 0.4275, 0.1876]],

         [[0.7862, 0.4917, 0.7873, 0.9167, 0.4198],
          [0.9768, 0.8646, 0.2155, 0.5702, 0.9009],
          [0.4889, 0.1771, 0.6247, 0.6206, 0.2799],
          [0.7839, 0.3831, 0.5594, 0.8454, 0.8190]],

         [[0.5639, 0.5741, 0.3243, 0.4780, 0.0151],
          [0.8184, 0.1632, 0.2789, 0.8391, 0.3525],
          [0.2624, 0.8875, 0.1239, 0.6427, 0.8983],
          [0.4057, 0.2296, 0.1108, 0.5752, 0.2447]]],


        [[[0.4859, 0.6594, 0.4121, 0.9914, 0.5925],
          [0.0426, 0.5293, 0.8782, 0.0217, 0.3668],
          [0.2364, 0.4685, 0.2407, 0.8943, 0.1536],
          [0.3783, 0.3578, 0.6183, 0.2764, 0.0956]],

         [[0.2503, 0.6317, 0.5188, 0.8541, 0.9529],
          [0.5606, 0.3444, 0.8909, 0.8288, 0.6941],
          [0.0117, 0.7705, 0.4337, 0.2811, 0.8015],
  