## 02. 텐서의 연산

In [3]:
import torch


### 2-1. 산술 연산

In [5]:
tensor = torch.rand(2,2)
print (tensor)
tensor = tensor * 2
print (tensor)
tensor = tensor + 1
print (tensor)



tensor([[0.9158, 0.3555],
        [0.9870, 0.5251]])
tensor([[1.8316, 0.7109],
        [1.9740, 1.0501]])
tensor([[2.8316, 1.7109],
        [2.9740, 2.0501]])


In [16]:
# 더하기
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x, y)

print(x+y)
# print(x*y)
# print(add)

# in-place 바꿔치기 연산
add = torch.add(x,y)
print(add)
y.add_(x)
print(y)

tensor([[1.5139, 0.3972],
        [1.0948, 1.0649]])
tensor([[1.5139, 0.3972],
        [1.0948, 1.0649]])
tensor([[1.5139, 0.3972],
        [1.0948, 1.0649]])


In [17]:
# 빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x, y)
print(x-y)
print(sub)

tensor([[ 0.2303, -0.6111],
        [ 0.0770, -0.2381]])
tensor([[ 0.2303, -0.6111],
        [ 0.0770, -0.2381]])


In [18]:
# 곱하기
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x, y)
print(x*y)
print(mul)

tensor([[0.3097, 0.0780],
        [0.6075, 0.3289]])
tensor([[0.3097, 0.0780],
        [0.6075, 0.3289]])


In [21]:
# 나누기
x = torch.rand(2,2)
y = torch.rand(2,2)
div = torch.div(x, y)
print(x/y)
print(div)

tensor([[9.0951, 5.0258],
        [0.8634, 2.3223]])
tensor([[9.0951, 5.0258],
        [0.8634, 2.3223]])
