## 02. 텐서의 연산

In [3]:
import torch


### 2-1. 산술 연산

In [5]:
tensor = torch.rand(2,2)
print (tensor)
tensor = tensor * 2
print (tensor)
tensor = tensor + 1
print (tensor)



tensor([[0.9158, 0.3555],
        [0.9870, 0.5251]])
tensor([[1.8316, 0.7109],
        [1.9740, 1.0501]])
tensor([[2.8316, 1.7109],
        [2.9740, 2.0501]])


In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x, y)

print(x,y)
# print(x*y)
# print(add)

# in-place 바꿔치기 연산
add = torch.add(x,y)
print(add)
y.add_(x)
print(y)

tensor([[0.0697, 0.0051],
        [0.6516, 0.3115]]) tensor([[0.4338, 0.3430],
        [0.1911, 0.7295]])
tensor([[0.5035, 0.3480],
        [0.8427, 1.0410]])
tensor([[0.5035, 0.3480],
        [0.8427, 1.0410]])
