## 03. Tensor의 조작


### 3-1. 인덱싱,슬라이싱
- numpy처럼 활용

In [1]:
import torch

In [11]:
tensor = torch.tensor([[1,2],[3,4]])
print(tensor[0,1])  # 2
print(tensor[0,:])  # [1,2]

a = torch.Tensor([1,2,3,4,5])
print(a[-2:])

b = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
c = b[b >  5]
d = b[b % 2 == 0]
e = b[[0,1],[1,2]]
e

tensor(2)
tensor([1, 2])
tensor([4., 5.])


tensor([2, 6])