## 03. Tensor의 조작


### 3-1. 인덱싱,슬라이싱
- numpy처럼 활용

In [1]:
import torch

In [11]:
tensor = torch.tensor([[1,2],[3,4]])
print(tensor[0,1])  # 2
print(tensor[0,:])  # [1,2]

a = torch.Tensor([1,2,3,4,5])
print(a[-2:])

b = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
c = b[b >  5]
d = b[b % 2 == 0]
e = b[[0,1],[1,2]]
e

tensor(2)
tensor([1, 2])
tensor([4., 5.])


tensor([2, 6])

### 3-2.Tensor의 크기,모양 변경

In [15]:
t = torch.rand(4,5)
print(t)
x = t.view(5,4)
print(x)
y = t.view(10,-1)
print(y)



tensor([[8.8899e-02, 1.3328e-03, 7.8765e-01, 9.1714e-01, 3.9962e-01],
        [1.9759e-01, 9.9814e-01, 5.6754e-01, 5.0013e-02, 3.8532e-02],
        [8.1570e-01, 7.1563e-01, 2.6631e-04, 5.1582e-01, 4.9079e-01],
        [7.8680e-01, 9.3211e-01, 5.5440e-01, 6.2802e-01, 8.6062e-01]])
tensor([[8.8899e-02, 1.3328e-03, 7.8765e-01, 9.1714e-01],
        [3.9962e-01, 1.9759e-01, 9.9814e-01, 5.6754e-01],
        [5.0013e-02, 3.8532e-02, 8.1570e-01, 7.1563e-01],
        [2.6631e-04, 5.1582e-01, 4.9079e-01, 7.8680e-01],
        [9.3211e-01, 5.5440e-01, 6.2802e-01, 8.6062e-01]])
tensor([[8.8899e-02, 1.3328e-03],
        [7.8765e-01, 9.1714e-01],
        [3.9962e-01, 1.9759e-01],
        [9.9814e-01, 5.6754e-01],
        [5.0013e-02, 3.8532e-02],
        [8.1570e-01, 7.1563e-01],
        [2.6631e-04, 5.1582e-01],
        [4.9079e-01, 7.8680e-01],
        [9.3211e-01, 5.5440e-01],
        [6.2802e-01, 8.6062e-01]])


### 3-3. Tensor의 숫자값 얻기

In [18]:
x = torch.tensor(10)
print(x.item())

y =torch.rand(1)
print(y)
print(y.item())

10
tensor([0.7642])
0.7642136812210083


### 3-4. 차원 축소와 증가

#### 3-4-1. 차원 축소(제거)
- torch.squeeze() : 크기가 1인 차원을 축소함

In [20]:
t = torch.rand(1,3,3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.7331, 0.8956, 0.7034],
         [0.1747, 0.8491, 0.1974],
         [0.3077, 0.8087, 0.6354]]])
torch.Size([1, 3, 3])
tensor([[0.7331, 0.8956, 0.7034],
        [0.1747, 0.8491, 0.1974],
        [0.3077, 0.8087, 0.6354]])
torch.Size([3, 3])


#### 3-4-2. 차원 증가(생성)
- torch.unsqueeze() : 지정한 위치에 새로운 차원을 생성

In [24]:
t = torch.rand(3,3,3)
print(t)
print(t.shape)

ts = torch.unsqueeze(t, 1)
print(ts)
print(ts.shape)

tensor([[[0.2612, 0.9575, 0.5988],
         [0.6138, 0.7911, 0.4257],
         [0.6618, 0.5696, 0.2748]],

        [[0.9613, 0.6073, 0.8582],
         [0.7310, 0.6014, 0.9635],
         [0.4147, 0.2688, 0.1376]],

        [[0.4136, 0.5829, 0.8742],
         [0.5359, 0.8004, 0.1093],
         [0.6487, 0.6138, 0.6495]]])
torch.Size([3, 3, 3])
tensor([[[[0.2612, 0.9575, 0.5988],
          [0.6138, 0.7911, 0.4257],
          [0.6618, 0.5696, 0.2748]]],


        [[[0.9613, 0.6073, 0.8582],
          [0.7310, 0.6014, 0.9635],
          [0.4147, 0.2688, 0.1376]]],


        [[[0.4136, 0.5829, 0.8742],
          [0.5359, 0.8004, 0.1093],
          [0.6487, 0.6138, 0.6495]]]])
torch.Size([3, 1, 3, 3])


### 3-5. 텐서간 결합
- 'torch.stack()' : 동일한 형식의 텐서를 새롭게 그룹화 함
    - 새로운 차원이 생성  

In [26]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
z = torch.stack((x,y))
print(z)
print(z.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


- 'torch.cat()' : 하나의 텐서로 병합
    - 새로운 차원 생성 X

In [29]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])

z = torch.cat((x,y), dim=0)
print(z)
print(z.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])


### 3-6. 텐서 나누니기
- 'torch.chunk'
    - 텐서를 몇개로 나눌지 지정
    - 나누어 떨어지지 않으면 마지막 조각은 크기가 다를 수 있음

In [37]:
t = torch.rand(3,3)
print(t)

x = torch.chunk(t, 3, dim=0)

print(x)

tensor([[0.2902, 0.6489, 0.8177],
        [0.0484, 0.9251, 0.4106],
        [0.7519, 0.6017, 0.5279]])
(tensor([[0.2902, 0.6489, 0.8177]]), tensor([[0.0484, 0.9251, 0.4106]]), tensor([[0.7519, 0.6017, 0.5279]]))


### 텐서
- torch.split()
    - 텐서의 크기를 기준으로 나눔


In [39]:
t = torch.tensor([1,2,3,4,5])
print(t)

x,y,z = torch.split(t, [2,2,1], dim=0)

print(x)
print(y)
print(z)


tensor([1, 2, 3, 4, 5])
tensor([1, 2])
tensor([3, 4])
tensor([5])
