## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [3]:
import torch
tensor=torch.tensor([2, 4, 6])
print(tensor+5)
print(tensor-3)

tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [12]:
tensor1=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor2=torch.tensor([[7,8,9],[10,11,12],[13,14,15]])
# print(tensor1)
# print(tensor2)
print(tensor1+tensor2)
print(tensor1-tensor2)
print(tensor1*tensor2)
print(tensor1/tensor2)


tensor([[ 8, 10, 12],
        [14, 16, 18],
        [20, 22, 24]])
tensor([[-6, -6, -6],
        [-6, -6, -6],
        [-6, -6, -6]])
tensor([[  7,  16,  27],
        [ 40,  55,  72],
        [ 91, 112, 135]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000],
        [0.5385, 0.5714, 0.6000]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [13]:
tensorA=torch.tensor([[1,2,3],[4,5,6]])

tensorB=torch.tensor([[7,8],[9,10],[11,12]])

print(torch.matmul(tensorA,tensorB))

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [16]:
tensorR=torch.tensor([[ 58,  64],[139, 154]])
tensorR+=10
print(tensorR)
clamp = torch.clamp(tensorR,max=100)
print(clamp)

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [17]:
tensorM=torch.tensor([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])

print(torch.sum(tensorM,dim=0))

tensor([55, 60, 65, 70, 75])
